# global configs
Global:
  checkpoints: null
  pretrained_model: null
  output_dir: ./output/
  device: gpu
  save_interval: 1
  eval_during_train: True
  eval_interval: 1
  epochs: 40
  print_batch_step: 10
  use_visualdl: False
  # used for static mode and model export
  image_shape: [3, 224, 224]  # reduced image size
  save_inference_dir: ./inference
  # training model under @to_static
  to_static: False
  use_multilabel: True

# model ema
EMA:
  decay: 0.9997

# mixed precision
AMP:
  use_amp: True
  use_fp16_test: False
  scale_loss: 128.0
  use_dynamic_loss_scaling: True
  use_promote: False
  # O1: mixed fp16, O2: pure fp16
  level: O1

# model architecture
Arch:
  name: MobileNetV3_x0_35  # even smaller model architecture
  class_num: 3
  pretrained: False  # disable pretrained weights
  use_sync_bn: True
# loss function config for training/eval process
Loss:
  Train:
    - MultiLabelAsymmetricLoss:
        weight: 1.0
        gamma_pos: 0
        gamma_neg: 4
        clip: 0.05
        disable_focal_loss_grad: True

  Eval:
    - MultiLabelAsymmetricLoss:
        weight: 1.0
        gamma_pos: 0
        gamma_neg: 4
        clip: 0.05
        disable_focal_loss_grad: True

Optimizer:
  name: AdamW
  one_dim_param_no_weight_decay: True
  weight_decay: 0.0001 # 1e-4
  lr:
    name: OneCycleLR
    max_learning_rate: 0.0001 # 1e-4
    divide_factor: 25.0
    end_learning_rate: 0.0000000001 # 1e-10
    phase_pct: 0.2
    anneal_strategy: cos
    three_phase: False

# data loader for train and eval
DataLoader:
  Train:
    dataset:
      name: MultiLabelDataset  # multi-label dataset class
      image_root: ./dataset/jpg/  # image directory
      cls_label_path: ./dataset/train_list.txt  # path to training labels
      transform_ops:
        - DecodeImage:
            to_rgb: True
            channel_first: False
        - ResizeImage:
            size: 224  # reduced image size
            interpolation: bilinear
            backend: pil
        - Cutout:
            length: 112  # adjusted for smaller image size
            fill_value: none
        - RandAugmentV4:
        - NormalizeImage:
            scale: 1.0/255.0
            mean: [0.485, 0.456, 0.406]
            std: [0.229, 0.224, 0.225]
            order: ''

    sampler:
      name: DistributedBatchSampler
      batch_size: 8  # reduced batch size for single GPU
      drop_last: False
      shuffle: True
    loader:
      num_workers: 4  # reduced number of workers for single GPU
      use_shared_memory: True

  Eval:
    dataset:
      name: MultiLabelDataset
      image_root: ./dataset/jpg/
      cls_label_path: ./dataset/test_list.txt
      transform_ops:
        - DecodeImage:
            to_rgb: True
            channel_first: False
        - ResizeImage:
            size: 224  # reduced image size
            interpolation: bilinear
            backend: pil
        - NormalizeImage:
            scale: 1.0/255.0
            mean: [0.485, 0.456, 0.406]
            std: [0.229, 0.224, 0.225]
            order: ''
    sampler:
      name: DistributedBatchSampler
      batch_size: 8  # reduced batch size for single GPU
      drop_last: False
      shuffle: False
    loader:
      num_workers: 4  # reduced number of workers for single GPU
      use_shared_memory: True

Infer:
  infer_imgs: dataset/infer_jpg/
  batch_size: 10
  transforms:
    - DecodeImage:
        to_rgb: True
        channel_first: False
    - ResizeImage:
        size: 224  # reduced image size
        interpolation: bilinear
        backend: pil
    - NormalizeImage:
        scale: 1.0/255.0
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]
        order: ''
    - ToCHWImage:
  PostProcess:
    name: MultiLabelThreshOutput
    threshold: 0.5
    class_id_map_file: "dataset/label_map.txt"

Metric:
  Train:
  Eval:
    - MultiLabelMAP:
        # support list: integral, 11point
        # default: integral
        map_type: integral
    - AccuracyScore:  # added accuracy metric