Global:
  infer_imgs: "./images/ImageNet/ILSVRC2012_val_00000010.jpeg"
  inference_model_dir: "./models"
  batch_size: 1
  use_gpu: False
  enable_mkldnn: True
  cpu_num_threads: 10
  enable_benchmark: True
  use_fp16: False
  ir_optim: True
  use_tensorrt: False
  gpu_mem: 8000
  enable_profile: False

PreProcess:
  transform_ops:
    - DecodeImage:
        to_rgb: True
        channel_first: False
    - ResizeImage:
        resize_short: 256
    - CropImage:
        size: 224
    - NormalizeImage:
        scale: 1.0/255.0
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]
        order: ''
    - ToCHWImage:

PostProcess:
  name: MultiLabelThreshOutput  # output processing for multi-label
  threshold: 0.5  # threshold for multi-label output
  class_id_map_file: "dataset/label_map.txt"
  delimiter: " 
